### ISSUE TITLE
Github Action implementation

### ISSUE THREAD

**Issue by GuillaumeFalourd** [stack-spot/cloud-deploy-action#1]
## Product Issue

https://github.com/stack-spot/cloud-backlog/issues/56

## Description

Implement a Github Action that will allow to deploy containerized applications using StackSpot Cloud, following the related [Event Storm journey](https://www.figma.com/board/a7RSmvrAHMz0uq54gk4BC5/Cloud-v1-Design?node-id=933-5829&t=9tf5FUAygFS2RUkv-4).

## DOD

- [ ] Action should be compatible with Ubuntu, Windows and MacOs runners.
- [ ] Action should support containerized applications.
- [ ] Action output should be available on StackSpot Cloud Portal as a new application deployment.

## Tasks

- [x] Create an `action.yaml` file setting a `composite` action calling a python script.
- [x] The python script should:
    - [x] Check inputs from an `application.yaml` file and return an error if one is missing.
    - [x] Authenticate in StackSpot IAM.
    - [x] Call a Cloud Platform API endpoint to deploy an application.
    - [x] Poll a Cloud Platform API endpoint to check deployment status.
- [ ] Create a github action workflow testing the action in STG.
